server:
  port: 40001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.4.93.222:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: zdy123456
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    static-path-pattern: classpath:/static
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口 465
    username: 1535661945@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: yiozwjncqetmiafb # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 1535661945@qq.com # 发送方邮件，配在yml中可方便更改

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dyingzhang.auth.domain.entity