server:
  port: 8080

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.4.93.222:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Zdy!230003#
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities